<a href="https://colab.research.google.com/github/sikendrapurampravalika-del/ML_LAB_2026-27/blob/main/KNN_algorithm.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [11]:
import numpy as np
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
# 1. Load the dataset
iris = load_iris()
X = iris.data  # Features (sepal length, sepal width, petal length, petal width)
y = iris.target # Target (species of iris)
# 2. Split the data into training and testing sets
# 70% for training, 30% for testing. random_state ensures reproducible results.
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)
# 3. Scale the features
# KNN is distance-based, so scaling features (e.g., to have 0 mean and unit variance)
# is crucial for good performance.
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)
# 4. Create and Train the KNN Classifier
# We'll start with k=5 (n_neighbors=5)
# 'n_neighbors' is the 'k' in KNN.
knn = KNeighborsClassifier(n_neighbors=5)
# Train the model (for KNN, this mostly just stores the data)
knn.fit(X_train, y_train)
# 5. Make Predictions
y_pred = knn.predict(X_test)
# 6. Evaluate the Model
accuracy = accuracy_score(y_test, y_pred)
print(f"--- Model Evaluation (k=5) ---")
print(f"Accuracy: {accuracy:.4f}")
print("\nClassification Report:")
print(classification_report(y_test, y_pred, target_names=iris.target_names))
print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred))
# 7. (Optional) Predict on a single new sample
# Let's invent a new flower and predict its species
# Note: The new sample must be scaled using the *same scaler*
new_flower = np.array([[5.1, 3.5, 1.4, 0.2]]) # A sample similar to the first iris
new_flower_scaled = scaler.transform(new_flower)
prediction = knn.predict(new_flower_scaled)
predicted_species = iris.target_names[prediction[0]]
print(f"\n--- New Prediction ---")
print(f"Prediction for {new_flower}: {predicted_species}")

--- Model Evaluation (k=5) ---
Accuracy: 1.0000

Classification Report:
              precision    recall  f1-score   support

      setosa       1.00      1.00      1.00        19
  versicolor       1.00      1.00      1.00        13
   virginica       1.00      1.00      1.00        13

    accuracy                           1.00        45
   macro avg       1.00      1.00      1.00        45
weighted avg       1.00      1.00      1.00        45


Confusion Matrix:
[[19  0  0]
 [ 0 13  0]
 [ 0  0 13]]

--- New Prediction ---
Prediction for [[5.1 3.5 1.4 0.2]]: setosa


In [9]:
import numpy as np
from sklearn.datasets import load_breast_cancer
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
# 1. Load the dataset
cancer = load_breast_cancer()
X = cancer.data
y = cancer.target
# 2. Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.3, random_state=42
    )
# 3. Scale the features
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)
# 4. Create and train the KNN classifier
knn = KNeighborsClassifier(n_neighbors=5)
knn.fit(X_train, y_train)
# 5. Make predictions
y_pred = knn.predict(X_test)
# 6. Evaluate the model
accuracy = accuracy_score(y_test, y_pred)
print("--- Model Evaluation (k=5) ---")
print(f"Accuracy: {accuracy:.4f}")
print("\nClassification Report:")
print(classification_report(
    y_test,
    y_pred,
    target_names=cancer.target_names
))
print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred))
# 7. Predict on a single sample
new_sample = cancer.data[0].reshape(1, -1)
new_sample_scaled = scaler.transform(new_sample)
prediction = knn.predict(new_sample_scaled)
predicted_diagnosis = cancer.target_names[prediction[0]]
print("\n--- New Prediction ---")
print(f"Predicted Diagnosis: {predicted_diagnosis}")

--- Model Evaluation (k=5) ---
Accuracy: 0.9591

Classification Report:
              precision    recall  f1-score   support

   malignant       0.95      0.94      0.94        63
      benign       0.96      0.97      0.97       108

    accuracy                           0.96       171
   macro avg       0.96      0.95      0.96       171
weighted avg       0.96      0.96      0.96       171


Confusion Matrix:
[[ 59   4]
 [  3 105]]

--- New Prediction ---
Predicted Diagnosis: malignant


In [16]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
# 1. Load the dataset
df = pd.read_csv("/content/KNNAlgorithmDataset")
print("Dataset loaded successfully!")
print(df.head())
# Remove unnecessary columns
df = df.drop(columns=["id", "Unnamed: 32"], errors="ignore")
# Features and target
X = df.drop(columns=["diagnosis"])
y = df["diagnosis"]
# Encode target labels
encoder = LabelEncoder()
y = encoder.fit_transform(y)
# 2. Split the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.3, random_state=42, stratify=y
)
# 3. Scale the features
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)
# 4. Create and train the KNN classifier
knn = KNeighborsClassifier(n_neighbors=5)
knn.fit(X_train, y_train)
# 5. Make predictions
y_pred = knn.predict(X_test)
# 6. Evaluate the model
accuracy = accuracy_score(y_test, y_pred)
print("\n--- Model Evaluation (k=5) ---")
print(f"Accuracy: {accuracy:.4f}")
print("\nClassification Report:")
print(classification_report(
    y_test,
    y_pred,
    target_names=encoder.classes_.astype(str)
))
print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred))
# 7. Predict on a single sample
new_sample = X.iloc[[0]]
new_sample_scaled = scaler.transform(new_sample)
prediction = knn.predict(new_sample_scaled)
predicted_diagnosis = encoder.inverse_transform(prediction)
print("\n--- New Prediction ---")
print("Predicted Diagnosis:", predicted_diagnosis[0])

Dataset loaded successfully!
         id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  texture_worst  perimeter_