<a href="https://colab.research.google.com/github/sikendrapurampravalika-del/ML_LAB_2026-27/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
list1 = [2,4,6,8]
array1 = np.array(list1)
print(array1)

[2 4 6 8]


In [3]:
array1 = np.array([[1,2,3,4],[9,6,7,8]])
print(array1)

[[1 2 3 4]
 [9 6 7 8]]


In [4]:
array1 = np.array([[[1,2,3,4],[5,6,7,8],[9,10,11,12]],[[13,14,15,16],[17,18,19,20],[21,22,23,24]]])
print(array1)

[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]


In [6]:

marks = np.array([1,2,3,4])
print(marks)

[1 2 3 4]


In [7]:
array1 = np.array([1,2,3,4])
print(array1.dtype)

int64


In [8]:
print(array1.ndim)

1


In [9]:
print(array1.size)

4


In [11]:
array1 = np.array([[1,2,3,4],[5,6,7,8]])
print(array1.shape)

(2, 4)


In [12]:
array1 = np.array([1, 2, 3, 4, 5])
median = np.median(array1)
print(median)



3.0


In [13]:
marks = np.array([75,85,95,65,25])
mean_marks = np.mean(marks)
print(mean_marks)

69.0


In [14]:
marks = np.array([75,85,95,65,25])
std_marks = np.std(marks)
print(std_marks)

24.166091947189145


In [15]:
marks = np.array([75,85,95,65,25])
std_marks = np.percentile(marks,80)
print(std_marks)

87.0


In [16]:
marks = np.array([75,85,95,65,25])
std_marks = np.min(marks)
print(std_marks)

25


In [17]:
marks = np.array([75,85,95,65,25])
std_marks = np.max(marks)
print(std_marks)

95


In [18]:
array1 = np.array([1,2,3,4,5,6])
print(array1[0])
print(array1[2])
print(array1[4])
print(array1[3])

1
3
5
4


In [22]:
array1 = np.array([5, 2, 8, 9, 12])
array2 = np.array([5, 2, 8, 9, 12], dtype=np.int32)
print(array1.itemsize)
print(array2.itemsize)

8
4


In [27]:
array1 = np.array([2, 4, 8])
array2 = np.array([[5, 7, 9],[6, 7, 8]])
print("\nData of array1 is: ",array1.data)
print("Data of array2 is: ",array2.data)


Data of array1 is:  <memory at 0x7f577545ff40>
Data of array2 is:  <memory at 0x7f577535f5e0>


In [26]:
array1[1] = 10
print(array1)

[ 2 10  8]


In [34]:
array1 = np.array([[2, 4, 6, 8],
                       [1, 3, 5, 7],
                       [9, 12, 14, 16]])
element1 = array1[2, 3]
print("4th Element at 2nd Row:",element1)
element2 = array1[0, 1]
print("2nd Element at First Row:",element2)

4th Element at 2nd Row: 16
2nd Element at First Row: 4


In [38]:
import numpy as np
x = np.array([1,2,3,4])
y = np.array([[5,6,7,8],[3,5,9,1]])
z = np.add(x,y)
print("Addition of x and y:\n", z)
z = np.subtract(x,y)
print("Subtraction of y from x:\n", z)
z = np.multiply(x,y)
print("Element-wise multiplication of x and y:\n", z)

Addition of x and y:
 [[ 6  8 10 12]
 [ 4  7 12  5]]
Subtraction of y from x:
 [[-4 -4 -4 -4]
 [-2 -3 -6  3]]
Element-wise multiplication of x and y:
 [[ 5 12 21 32]
 [ 3 10 27  4]]


In [37]:
import numpy as np
my_array = np.array([2,4,6,8])
print("my_array before appending:", my_array)
new_array = np.append(my_array, [1,3,5,7])
print("new_array:", new_array)
print("my_array after appending:", my_array)

my_array before appending: [2 4 6 8]
new_array: [2 4 6 8 1 3 5 7]
my_array after appending: [2 4 6 8]


In [46]:
import numpy as np
my_2d_array = np.array([[2,4,6,8], [10,12,14,16]], dtype=np.int64)
print("my_2d_array before appending:\n", my_2d_array)
new_2d_array = np.append(my_2d_array, [[4], [5]], axis=1)
print("new_2d_array:\n", new_2d_array)
print("my_2d_array after appending:\n", my_2d_array)


my_2d_array before appending:
 [[ 2  4  6  8]
 [10 12 14 16]]
new_2d_array:
 [[ 2  4  6  8  4]
 [10 12 14 16  5]]
my_2d_array after appending:
 [[ 2  4  6  8]
 [10 12 14 16]]


In [43]:
import numpy as np
my_array = np.array([2,4,6,8])
my_2d_array = np.array([[2,4,6,8], [10,12,14,16]], dtype=np.int64)
np.insert(my_array, 2, 10)
np.delete(my_array,[2])

array([2, 4, 8])